[theme]
primaryColor = "#002B49"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#EDF0F2"
textColor = "#000000"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
